2023-05-12 19:44:11 - ERROR - Response from 'RU' is not OK (status code is not 200). Check the URL.
=> Process stopped.
2023-05-12 19:44:23 - ERROR - Response from 'BE' is not OK (status code is not 200). Check the URL.
=> Process stopped.
2023-05-12 20:26:29 - ERROR - This event loop is already running
Traceback (most recent call last):
  File "/Users/Sasha/Documents/PythonProjects/Varta/multiproc_authors_4.py", line 68, in get_response_per_scroll
    js_out = response.html.render(timeout=30, sleep=2, script=js_script_down)
  File "/Users/Sasha/Documents/PythonProjects/Varta/venv/lib/python3.10/site-packages/requests_html.py", line 598, in render
    content, result, page = self.session.loop.run_until_complete(self._async_render(url=self.url, script=script, sleep=sleep, wait=wait, content=self.html, reload=reload, scrolldown=scrolldown, timeout=timeout, keep_page=keep_page))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
  File "/Users/Sasha/Documents/PythonProjects/Varta/venv/lib/python3.10/site-packages/pyppeteer/launcher.py", line 153, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 622, in run_until_complete
    self._check_running()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2023-05-12 20:26:29 - ERROR - This event loop is already running
Traceback (most recent call last):
  File "/Users/Sasha/Documents/PythonProjects/Varta/multiproc_authors_4.py", line 68, in get_response_per_scroll
    js_out = response.html.render(timeout=30, sleep=2, script=js_script_down)
  File "/Users/Sasha/Documents/PythonProjects/Varta/venv/lib/python3.10/site-packages/requests_html.py", line 598, in render
    content, result, page = self.session.loop.run_until_complete(self._async_render(url=self.url, script=script, sleep=sleep, wait=wait, content=self.html, reload=reload, scrolldown=scrolldown, timeout=timeout, keep_page=keep_page))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
  File "/Users/Sasha/Documents/PythonProjects/Varta/venv/lib/python3.10/site-packages/pyppeteer/launcher.py", line 153, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 622, in run_until_complete
    self._check_running()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2023-05-12 20:26:29 - ERROR - This event loop is already running
Traceback (most recent call last):
  File "/Users/Sasha/Documents/PythonProjects/Varta/multiproc_authors_4.py", line 68, in get_response_per_scroll
    js_out = response.html.render(timeout=30, sleep=2, script=js_script_down)
  File "/Users/Sasha/Documents/PythonProjects/Varta/venv/lib/python3.10/site-packages/requests_html.py", line 598, in render
    content, result, page = self.session.loop.run_until_complete(self._async_render(url=self.url, script=script, sleep=sleep, wait=wait, content=self.html, reload=reload, scrolldown=scrolldown, timeout=timeout, keep_page=keep_page))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
  File "/Users/Sasha/Documents/PythonProjects/Varta/venv/lib/python3.10/site-packages/pyppeteer/launcher.py", line 153, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 622, in run_until_complete
    self._check_running()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2023-05-12 22:44:00 - ERROR - This event loop is already running
Traceback (most recent call last):
  File "/Users/Sasha/Documents/PythonProjects/Varta/multiproc_authors_4.py", line 68, in get_response_per_scroll
    js_out = response.html.render(timeout=30, sleep=2, script=js_script_down)
  File "/Users/Sasha/Documents/PythonProjects/Varta/venv/lib/python3.10/site-packages/requests_html.py", line 598, in render
    content, result, page = self.session.loop.run_until_complete(self._async_render(url=self.url, script=script, sleep=sleep, wait=wait, content=self.html, reload=reload, scrolldown=scrolldown, timeout=timeout, keep_page=keep_page))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
  File "/Users/Sasha/Documents/PythonProjects/Varta/venv/lib/python3.10/site-packages/pyppeteer/launcher.py", line 153, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 622, in run_until_complete
    self._check_running()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2023-05-12 22:44:00 - ERROR - This event loop is already running
Traceback (most recent call last):
  File "/Users/Sasha/Documents/PythonProjects/Varta/multiproc_authors_4.py", line 68, in get_response_per_scroll
    js_out = response.html.render(timeout=30, sleep=2, script=js_script_down)
  File "/Users/Sasha/Documents/PythonProjects/Varta/venv/lib/python3.10/site-packages/requests_html.py", line 598, in render
    content, result, page = self.session.loop.run_until_complete(self._async_render(url=self.url, script=script, sleep=sleep, wait=wait, content=self.html, reload=reload, scrolldown=scrolldown, timeout=timeout, keep_page=keep_page))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
  File "/Users/Sasha/Documents/PythonProjects/Varta/venv/lib/python3.10/site-packages/pyppeteer/launcher.py", line 153, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 622, in run_until_complete
    self._check_running()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2023-05-12 22:44:00 - ERROR - This event loop is already running
Traceback (most recent call last):
  File "/Users/Sasha/Documents/PythonProjects/Varta/multiproc_authors_4.py", line 68, in get_response_per_scroll
    js_out = response.html.render(timeout=30, sleep=2, script=js_script_down)
  File "/Users/Sasha/Documents/PythonProjects/Varta/venv/lib/python3.10/site-packages/requests_html.py", line 598, in render
    content, result, page = self.session.loop.run_until_complete(self._async_render(url=self.url, script=script, sleep=sleep, wait=wait, content=self.html, reload=reload, scrolldown=scrolldown, timeout=timeout, keep_page=keep_page))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
  File "/Users/Sasha/Documents/PythonProjects/Varta/venv/lib/python3.10/site-packages/pyppeteer/launcher.py", line 153, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 622, in run_until_complete
    self._check_running()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2023-05-12 22:48:17 - INFO - 536 authors are collected from the site.
2023-05-12 23:01:32 - INFO - 536 authors are collected from the site.
2023-05-12 23:03:38 - INFO - 536 authors are added to the 'MAsync_2023.05.12__23:03.json'
2023-05-12 23:03:38 - INFO - => Process finished successfully!
Async time: 0:02:30.523290

2023-05-13 00:16:16 - INFO - 536 authors are collected from the site.
2023-05-13 00:19:03 - INFO - In lang 'EN' are 367 authors
2023-05-13 00:19:03 - INFO - In lang 'BE' are 458 authors
2023-05-13 00:19:03 - INFO - In lang 'RU' are 392 authors
2023-05-13 00:19:33 - INFO - 536 authors are collected from the site.
2023-05-13 00:21:34 - INFO - 536 authors are added to the 'MAsync_2023.05.13__00:21.json'
2023-05-13 00:21:34 - INFO - => Process finished successfully!
Async time: 0:03:29.876235

2023-05-13 00:24:10 - INFO - In lang 'EN' are 567 authors
2023-05-13 00:24:10 - INFO - In lang 'BE' are 554 authors
2023-05-13 00:24:10 - INFO - In lang 'RU' are 277 authors
2023-05-13 00:24:46 - INFO - 568 authors are collected from the site.
2023-05-13 00:26:43 - INFO - '6th Line' has 1 empty event
2023-05-13 00:26:55 - INFO - 568 authors are added to the 'MAsync_2023.05.13__00:26.json'
2023-05-13 00:26:55 - INFO - => Process finished successfully!
Async time: 0:04:07.419000

2023-05-13 00:30:03 - INFO - In lang 'EN' are 567 authors
2023-05-13 00:30:03 - INFO - In lang 'BE' are 560 authors
2023-05-13 00:30:03 - INFO - In lang 'RU' are 524 authors
2023-05-13 00:30:14 - INFO - 568 authors are collected from the site.
2023-05-13 00:32:06 - INFO - '6th Line' has 1 empty event
2023-05-13 00:32:30 - INFO - 568 authors are added to the 'MAsync_2023.05.13__00:32.json'
2023-05-13 00:32:30 - INFO - => Process finished successfully!
Async time: 0:04:22.502029

2023-05-13 00:39:51 - INFO - In lang 'EN' are 567 authors
2023-05-13 00:39:51 - INFO - In lang 'BE' are 560 authors
2023-05-13 00:39:51 - INFO - In lang 'RU' are 524 authors
2023-05-13 00:40:01 - INFO - 568 authors are collected from the site.
2023-05-13 00:41:22 - INFO - '6th Line' has 1 empty event
2023-05-13 00:42:19 - INFO - 568 authors are added to the 'MAsync_2023.05.13__00:42.json'
2023-05-13 00:42:19 - INFO - => Process finished successfully!
Async time: 0:06:20.828376

2023-05-13 00:48:23 - INFO - In function 'get_response_per_scroll()' were used: SCROLLS=5, SCROLL_HEIGHT=150
2023-05-13 00:48:24 - INFO - In lang 'EN' are 567 authors
2023-05-13 00:48:24 - INFO - In lang 'BE' are 560 authors
2023-05-13 00:48:24 - INFO - In lang 'RU' are 524 authors
2023-05-13 00:48:34 - INFO - 568 authors are collected from the site.
2023-05-13 00:50:10 - INFO - '6th Line' has 1 empty event
2023-05-13 00:50:59 - INFO - 568 authors are added to the 'MAsync_2023.05.13__00:50.json'
2023-05-13 00:50:59 - INFO - => Process finished successfully!
Async time: 0:04:14.335564

2023-05-13 00:57:18 - INFO - In function 'get_response_per_scroll()' were used: SCROLLS=5, SCROLL_HEIGHT=200
2023-05-13 00:57:18 - INFO - In lang 'EN' are 567 authors
2023-05-13 00:57:18 - INFO - In lang 'BE' are 554 authors
2023-05-13 00:57:18 - INFO - In lang 'RU' are 277 authors
2023-05-13 00:57:49 - INFO - 568 authors are collected from the site.
2023-05-13 00:59:05 - INFO - '6th Line' has 1 empty event
2023-05-13 01:00:09 - INFO - 568 authors are added to the 'MAsync_2023.05.13__01:00.json'
2023-05-13 01:00:09 - INFO - => Process finished successfully!
Async time: 0:04:19.693762

2023-05-13 01:08:51 - INFO - SCROLLS=4, SCROLL_HEIGHT=200
2023-05-13 01:08:51 - INFO - In lang 'EN' are 567 authors
2023-05-13 01:08:51 - INFO - In lang 'BE' are 554 authors
2023-05-13 01:08:51 - INFO - In lang 'RU' are 524 authors
2023-05-13 01:09:03 - INFO - 568 authors are collected from the site.
2023-05-13 01:10:07 - INFO - '6th Line' has 1 empty event
2023-05-13 01:11:28 - INFO - 568 authors are added to the 'MAsync_2023.05.13__01:11.json'
2023-05-13 01:11:28 - INFO - => Process finished successfully!
Async time: 0:04:19.236365

2023-05-13 01:19:15 - INFO - SCROLLS=5, SCROLL_HEIGHT=150
2023-05-13 01:19:15 - INFO - In lang 'EN' are 567 authors
2023-05-13 01:19:15 - INFO - In lang 'BE' are 560 authors
2023-05-13 01:19:15 - INFO - In lang 'RU' are 524 authors
2023-05-13 01:19:25 - INFO - 568 authors are collected from the site.
2023-05-13 01:20:15 - INFO - '6th Line' has 1 empty event
2023-05-13 01:21:39 - INFO - 568 authors are added to the 'MAsync_2023.05.13__01:21.json'
2023-05-13 01:21:39 - INFO - => Process finished successfully!
Async time: 0:04:05.984885

